Language = English
F
Allow run copies
Yes
Associate with extensions

Auto scroll minSize height
0
Auto scroll minSize width
0
Auto scroll position X
0
Auto scroll position Y
0
AutoRun
No
Back color
Sys
Background image
Nothing
Background image layout
Tile
Context menu
Nothing
Control box
Yes
Cursor
Default
Enabled
Yes
Forbid close
No
Forbid maximize
No
Forbid minimize
No
Fore color
Black
Form border style
Normal
Height
320
Icon
Nothing
Index
0
Main form
Yes
Main menu strip
Nothing
Maximum height
0
Maximum width
0
Minimum height
0
Minimum width
0
Name
Main
Opacity
100
Scroll
No
Show icon
Yes
Show in taskbar
Yes
Show in tray
No
Start position
Center screen
Tab index
0
Tab stop
Yes
Tag

Text
Hello world!
ToolTip

TopMost
No
Transparentcy key
Nothing
Visible
Yes
Width
500
Window state
Normal
X
0
Y
0
#Conteiner

#HistoryLevel
1
#TreeNode
#Parent
Main(0)
#Index
0
Main
Main
window
window
Obj
#End

B
Anchor
Left_top
Auto ellipsis
Yes
Back color
Nothing
Background image
Nothing
Background image layout
Tile
Context menu
Nothing
Cursor
Default
Dock
Nothing
Enabled
Yes
Flat style
Default
Font bold
No
Font family
Ubuntu
Font italic
No
Font size
8
Font strikeout
No
Font underline
No
Fore color
Black
Height
23
Image
Nothing
Image align
Center
Index
0
Maximum height
0
Maximum width
0
Minimum height
0
Minimum width
0
Name
btn
Padding bottom
0
Padding left
0
Padding right
0
Padding top
0
Tab index
0
Tab stop
Yes
Tag

Text
Click me
Text align
center
Text image relation
Overlay
ToolTip

Visible
Yes
Width
75
X
212
Y
148
#Conteiner
Main.Main[0]
#HistoryLevel
0
#TreeNode
#Parent
Main(0)
#Index
1
btn
btn
button
button
Obj
 Click
 2021089275a06dbd645a40ae573a0a9a
 Click
 Click
 Sobyt
  Main.Main.Hide
  ifWaLGUKYs
  deist
  deist
  Deist
  Main.Main.Show
  wkYJTKsmVh
  deist
  deist
  Deist
  IF Main.Main.Text = Main.Main.Text THEN
  imKCUsPkPV
  if
  if
  If
   Add actions here
   kxWoVRfHjq
   Nothing
   Nothing
   EmptyIf
  ELSEIF Main.Main.Text = Main.Main.Text THEN
  FixlkfuIQi
  elseif
  elseif
  ElseIf
   Add actions here
   McNrJrDQKq
   Nothing
   Nothing
   EmptyIf
  Else
  UcdliMNMGX
  else
  else
  Else
   Add actions here
   NxxGBuvPHc
   Nothing
   Nothing
   EmptyIf
  End If
  FBigxjlWSG
  endif
  endif
  EndIf
  WHILE Main.Main.Text = Main.Main.Text
  SfSeSuTUFQ
  while
  while
  While
   _Useful objects._Interrupts._Break loop
   twmlNovNWH
   deist
   deist
   Deist
  End While
  pjtCnvCrKj
  endwhile
  endwhile
  EndWhile
  Your explanatory comment
  NHAXDXgEMD
  comm
  comm
  Comm
#End

M
Enabled
Yes
Index
0
Name
Memory1
Tag

Value

X
4
Y
4
#Conteiner
Main.Main[0]
#HistoryLevel
2
#TreeNode
#Parent
Main(0)
#Index
2
Memory1
Memory1
memory
memory
Obj
#End

#ProjectParams
#PoleznieDistance
25
#EndPoleznieDistance
#Expands
Main
btn
2021089275a06dbd645a40ae573a0a9a
imKCUsPkPV
FixlkfuIQi
UcdliMNMGX
SfSeSuTUFQ
#EndExpands
#SelNode
NxxGBuvPHc
#ActiveForm
Main.Main[0]
#ActiveObj
Main.Main[0]
#ImagePath
Рисунки\
#ImageDefName
Image
#pProgressForm
yes
#Icon

#EndProjectParams
