Language = English

F
Name
Main
Text
Hello world
#Conteiner

#TreeNode
Main
Main
window
window
Obj
#End

B
Font family
Ubuntu
Name
btn
Text
Click me
#Conteiner
Main.Main[0]
#TreeNode
btn
btn
button
button
Obj
 Click
 2a6bb208d5436b107fb626a28ef53f9e
 Click
 Click
 Sobyt
  if Main.Main.Text = "a" then
  8607084e0b4d107a6921c888dc5d7f29
  if
  if
  If
   Main.Main.Text = "b"
   d118a88071003c8d78a4be78d9768577
   deist
   deist
   Deist
  elseif Main.Main.Text = "b" then
  404028c45b81bdd9203d70c7c26b9610
  elseif
  elseif
  ElseIf
   Main.Main.Text = "c"
   4fac803605138484b56dac5237cc5741
   deist
   deist
   Deist
  elseif Main.Main.Text = "c" then
  e1d98a6ba4d85defd34ffc3dcbc47829
  elseif
  elseif
  ElseIf
   Main.Main.Close
   8511af036dabcefabcb1cb70ace7f1b2
   deist
   deist
   Deist
  else
  257e927da7001a7b624c893507afdc86
  else
  else
  Else
   _Useful objects._Show messange._Show message("Hello!", Ok, Default, "Hello")
   e04f09b76783e3679cb00eb9407d2f8f
   deist
   deist
   Deist
   Main.Main.Text = "a"
   f88e0c6e5fe72bc9967792fe60f79dd0
   deist
   deist
   Deist
  endif
  ab3962a0b323d9fcdf31b6fe188e7f17
  endif
  endif
  EndIf
  while Main.Main.Text = Main.Main.Text
  e17e39ce08458dbdecb489e79db1fc6c
  while
  while
  While
   _Useful objects._Interrupts._Break loop
   5a8a43981ab684e2484e6db626ac1ace
   deist
   deist
   Deist
  endwhile
  a5d0f416f7fd3eeea5d1bb165fb4c182
  endwhile
  endwhile
  EndWhile
  # Your explanatory comment
  cdb53609729fa70150259c32234262ef
  comm
  comm
  Comm
#End
