Language = English

F
Name
Main
Text
Hello world!
#Conteiner

#TreeNode
Main
Main
window
window
Obj
#End

B
Font family
Ubuntu
Name
btn
Text
Click me
#Conteiner
Main.Main[0]
#TreeNode
btn
btn
button
button
Obj
 Click
 2021089275a06dbd645a40ae573a0a9a
 Click
 Click
 Sobyt
  _Useful objects._Show messange._Show message("Hello!", Ok, Default, "Hello")
  d46c31b5df383184251b4c48cf8581a9
  deist
  deist
  Deist
#End
